/// AUTOGENERATED TEST ///
#include "lfs.h"
#include "emubd/lfs_emubd.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

// lfs declarations
lfs_t lfs;
lfs_emubd_t bd;

#ifndef LFS_READ_SIZE
#define LFS_READ_SIZE 16
#endif

#ifndef LFS_PROG_SIZE
#define LFS_PROG_SIZE 16
#endif

#ifndef LFS_CACHE_SIZE
#define LFS_CACHE_SIZE 64
#endif

#ifndef LFS_BLOCK_SIZE
#define LFS_BLOCK_SIZE 512
#endif

#ifndef LFS_BLOCK_COUNT
#define LFS_BLOCK_COUNT 1024
#endif

#ifndef LFS_LOOKAHEAD_SIZE
#define LFS_LOOKAHEAD_SIZE 128
#endif

#ifndef LFS_FILE_SIZE
#define LFS_FILE_SIZE 32
#endif

#ifndef LFS_FILE_COUNT
#define LFS_FILE_COUNT 32
#endif

const struct lfs_config cfg = {
    .context = &bd,
    .read  = &lfs_emubd_read,
    .prog  = &lfs_emubd_prog,
    .erase = &lfs_emubd_erase,
    .sync  = &lfs_emubd_sync,

    .read_size      = LFS_READ_SIZE,
    .prog_size      = LFS_PROG_SIZE,
    .cache_size     = LFS_CACHE_SIZE,
    .block_size     = LFS_BLOCK_SIZE,
    .block_count    = LFS_BLOCK_COUNT,
    .lookahead_size = LFS_LOOKAHEAD_SIZE,
};

// Entry point
int main(void) {
    lfs_emubd_create(&cfg, "blocks");

    bd.stats.read_count = 0;
    bd.stats.prog_count = 0;
    bd.stats.erase_count = 0;

    int err = lfs_format(&lfs, &cfg);
    LFS_ASSERT(!err);

    err = lfs_mount(&lfs, &cfg);
    LFS_ASSERT(!err);

    srand(0);
    for (int i = 0; i < LFS_FILE_COUNT; i++) {
        char name[64];
        uint8_t data[LFS_FILE_SIZE];
        sprintf(name, "test%d", i);
        lfs_file_t file;
        err = lfs_file_open(&lfs, &file, name,
                LFS_O_CREAT | LFS_O_EXCL | LFS_O_WRONLY);
        LFS_ASSERT(!err);

        for (int j = 0; j < LFS_FILE_SIZE; j++) {
            data[j] = rand();
        }

        err = lfs_file_write(&lfs, &file, data, LFS_FILE_SIZE);
        LFS_ASSERT(err == LFS_FILE_SIZE);
        
        err = lfs_file_close(&lfs, &file);
        LFS_ASSERT(!err);
    }

    srand(0);
    for (int i = 0; i < LFS_FILE_COUNT; i++) {
        char name[64];
        uint8_t data[LFS_FILE_SIZE];
        sprintf(name, "test%d", i);
        lfs_file_t file;
        err = lfs_file_open(&lfs, &file, name, LFS_O_RDONLY);
        LFS_ASSERT(!err);

        err = lfs_file_read(&lfs, &file, data, LFS_FILE_SIZE);
        LFS_ASSERT(err == LFS_FILE_SIZE);

        for (int j = 0; j < LFS_FILE_SIZE; j++) {
            LFS_ASSERT(data[j] == (uint8_t)rand());
        }
        
        err = lfs_file_close(&lfs, &file);
        LFS_ASSERT(!err);
    }

    uint64_t size = lfs_fs_size(&lfs);

    err = lfs_unmount(&lfs);
    LFS_ASSERT(!err);

    lfs_emubd_destroy(&cfg);

    printf("%d %d = %lu %lu %lu %lu\n",
            LFS_FILE_COUNT,
            LFS_FILE_SIZE,
            bd.stats.read_count,
            bd.stats.prog_count,
            bd.stats.erase_count,
            size * (uint64_t)LFS_BLOCK_SIZE);
}
